// import '../global.css'

export const metadata = {
  title: 'About Section',
  description: 'Generated by create next app',
}

export default function AboutLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
