import './globals.css'
import { Montserrat } from 'next/font/google'


export const metadata = {
  title: 'My Movie App',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  weight:["400","700"],
  subsets : ["latin"],
  variable : "--font-main",
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>{children}</body>
    </html>
  )
}
